---
title: "5 Popular"
author: "Dr. Williams"
date: "3/30/2022"
output: html_document
---


1. Explain valence and energy
2. Show an empty plot
(Traditional R Shiny)
(Questions in Google Survey)
3. Develop questions based on characteristics of each artist
4. Develop questions about different songs on a particular 












```{r}
df = data.frame(x = c(0,0), y = c(0,0))
df %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() + 
  geom_vline(xintercept = 0.5,size = 1) +
  geom_hline(yintercept = 0.5,size = 1) +
  xlim(0,1) +
  ylim(0,1) +
  labs(x = 'Valence') +
  labs( y = 'Energy') +
  annotate("text", x=0.22, y=0.25, label= "Sad",size = 17.5, color = 'gray') +
  annotate("text", x=0.75, y=0.25, label= "Chill",size = 17.5, color = 'gray') +
  annotate("text", x=0.22, y=0.75, label= "Anger",size = 17.5, color = 'gray') +
  annotate("text", x=0.75, y=0.75, label= "Happy",size = 17.5, color = 'gray') +
  annotate("text", x=0.22, y=0.5, label= "Bad Feeling",size = 12.5, color = 'gray') +
  annotate("text", x=0.77, y=0.5, label= "Good Feeling",size = 12.5, color = 'gray') +
  theme_bw() +
  theme(axis.title = element_text(size = 18))


```












```{r}
library(tidyverse)
library(spotifyr)
library(lubridate)
access_token <- get_spotify_access_token()
```

http://www.rcharlie.net/sentify/

Drake
Kanye West
Taylor Swift
Carrie Underwood
Ed Sheeran
Adele

```{r}

## Get Tracks
drake_df = get_artist_audio_features('Drake')
kw_df = get_artist_audio_features('Kanye West')
ts_df = get_artist_audio_features('Taylor Swift')
cu_df = get_artist_audio_features('Carrie Underwood')
es_df = get_artist_audio_features('Ed Sheeran')
adele_df = get_artist_audio_features('Adele')
```

```{r}
df = bind_rows(drake_df,kw_df,ts_df,cu_df,es_df,adele_df)
```

Plotly like on website
```{r}
df %>% 
  filter(artist_name %in% c('Adele','Kanye West')) %>% 
  ggplot(aes(x = energy, y = valence, color = artist_name)) +
  geom_point() +
  geom_vline(xintercept = 0.5,size = 1) +
  geom_hline(yintercept = 0.5,size = 1) +
  theme_bw()
```


