---
title: "Untitled"
author: "Dr. Williams"
date: "3/29/2022"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(corrplot)
library(reshape2)
```




```{r echo=FALSE, message=FALSE, warning=FALSE}
artists_df = readRDS("artists.RData")
songs_df = readRDS("topArtistsSongs.RData")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
genre_df = artists_df %>% 
  select(name, genre) %>% 
  rename(artist_name = name)

## Only Interested Variable
in_df = songs_df %>% 
  select("danceability","energy","loudness","speechiness","acousticness","instrumentalness","liveness","valence", "tempo","duration_ms","popularity","artist_name") %>% 
  left_join(genre_df,by = 'artist_name')
```



## All Genres
```{r echo=FALSE, message=FALSE, warning=FALSE}
all_cor = in_df %>% 
  select(-artist_name,-genre) %>% 
  cor() 
  
all_cor_df = all_cor %>% 
  melt() %>% 
  # subset(abs(value)>.30) %>% 
  mutate(genre = 'all')
  
all_cor %>%   
corrplot()
```

## Country Music
```{r echo=FALSE, message=FALSE, warning=FALSE}
country_cor = in_df %>% 
  filter(genre == 'country') %>% 
  select(-artist_name,-genre) %>% 
  cor()

country_cor_df = country_cor %>% 
  melt() %>% 
  # subset(abs(value)>.30) %>% 
  mutate(genre = 'country')



country_cor %>% 
  corrplot()
```










## Hip Hop Music
```{r echo=FALSE, message=FALSE, warning=FALSE}
hiphop_cor = in_df %>% 
  filter(genre == 'hip-hop') %>% 
  select(-artist_name,-genre) %>% 
  cor() 
hiphop_cor_df = hiphop_cor %>% 
  melt() %>% 
  # subset(abs(value)>.30) %>% 
  mutate(genre = 'hiphop')


hiphop_cor %>% 
  corrplot()
```





## Jazz Music
```{r echo=FALSE, message=FALSE, warning=FALSE}
jazz_cor = in_df %>% 
  filter(genre == 'jazz') %>% 
  select(-artist_name,-genre) %>% 
  cor() 
jazz_cor_df = jazz_cor %>% 
  melt() %>% 
  # subset(abs(value)>.30) %>% 
  mutate(genre = 'jazz')

jazz_cor %>% 
  corrplot()
```


## Pop Music
```{r echo=FALSE, message=FALSE, warning=FALSE}
pop_cor = in_df %>% 
  filter(genre == 'pop') %>% 
  select(-artist_name,-genre) %>% 
  cor() 
pop_cor_df = pop_cor %>% 
  melt() %>% 
  # subset(abs(value)>.30) %>% 
  mutate(genre = 'pop')


pop_cor %>% 
  corrplot()
```


## R n B Music
```{r echo=FALSE, message=FALSE, warning=FALSE}
rnb_cor  = in_df %>% 
  filter(genre == 'r&b') %>% 
  select(-artist_name,-genre) %>% 
  cor() 


rnb_cor_df = rnb_cor %>% 
  melt() %>% 
  # subset(abs(value)>.30) %>% 
  mutate(genre = 'rnb')
rnb_cor %>% 
  corrplot()
```



```{r}
## Method to determine which pair of correlations is most different from one another
genre_cor_df = bind_rows(country_cor_df,hiphop_cor_df,
                         pop_cor_df,rnb_cor_df,jazz_cor_df) %>% 
  filter(Var1 != Var2) %>% 
  mutate(comb_var = paste0(Var1,'-',Var2))
```



```{r}
combinations_df = genre_cor_df %>%  
  group_by(comb_var) %>% 
  summarise(size = n(),
            mean = mean(value, na.rm = TRUE),
            sd = sd(value, na.rm = TRUE)
            )
```

