---
title: "Untitled"
author: "Dr. Williams"
date: "3/30/2022"
output: html_document
---

```{r}
library(tidyverse)
library(scales)
```



```{r}
artists_df = readRDS("songsPresentation.RData")
```



```{r}
df = data.frame(x = c(0,1), y = c(0,1))
p1 = df %>% 
  ggplot(aes(x = x, y = y)) +
  geom_blank() +
  geom_vline(xintercept = 0,size = 1) +
  geom_hline(yintercept = 0.5,size = 1) +
  scale_x_continuous(limits = c(-1,1), 
                     expand = c(0, 0),
                     labels = label_number(accuracy = 0.1)) +
  scale_y_continuous(limits = c(0,1), expand = c(0, 0))  +
  theme_bw() +
  theme(axis.title = element_text(size = 18, face = 'bold')) +
  geom_rect(aes(xmin=-1, xmax=0, ymin=0, ymax=1),alpha = 0.2, fill = 'red') +
  geom_rect(aes(xmin=0, xmax=1, ymin=0, ymax=1),alpha = 0.2, fill = 'blue') +
  labs(x = 'Valence',y='Energy') +
  theme(axis.text = element_text(size = 12, face = 'bold'),
        plot.margin = margin(0.3, 0.5, 0.1, 0.5, "cm")
  )


```



```{r}
tmp_df = artists_df  %>% 
  filter(artist_name == 'Pharrell Williams') %>% 
  mutate(m1_valence = 2*valence - 1) 
p1 +
  geom_point(data = tmp_df,aes(x =m1_valence  , y = energy, color = album_name))
```

